const ChatActionsTypes = {
	GET_CHATS: 'GET_CHATS',
	GET_CHATS_SUCCESS: 'GET_CHATS_SUCCESS',
	GET_CHATS_FAILURE: 'GET_CHATS_FAILURE',
	CREATE_CHAT: 'CREATE_CHAT',
	CREATE_CHAT_SUCCESS: 'CREATE_CHAT_SUCCESS',
	CREATE_CHAT_FAILURE: 'CREATE_CHAT_FAILURE'
};

export default ChatActionsTypes;
