const ThingActionsTypes = {
	GET_THINGS: 'GET_THINGS',
	GET_THINGS_SUCCESS: 'GET_THINGS_SUCCESS',
	GET_THINGS_FAILURE: 'GET_THINGS_FAILURE',
	ADD_THING: 'ADD_THING',
	ADD_THING_SUCCESS: 'ADD_THING_SUCCESS',
	ADD_THING_FAILURE: 'ADD_THING_FAILURE'
};

export default ThingActionsTypes;
