const UserActionTypes = {
	SET_CURRENT_USER: 'SET_CURRENT_USER',
	UPDATE_CURRENT_USER_INFO: 'UPDATE_CURRENT_USER_INFO',
	UPDATE_CURRENT_USER_INFO_SUCCESS: 'UPDATE_CURRENT_USER_INFO_SUCCESS',
	UPDATE_CURRENT_USER_INFO_FAILURE: 'UPDATE_CURRENT_USER_INFO_FAILURE',
	GOOGLE_SING_IN_START: 'GOOGLE_SING_IN_START',
	SING_IN_SUCCESS: 'SING_IN_SUCCESS',
	SING_IN_FAILURE: 'SING_IN_FAILURE',
	EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
	CHECK_USER_SESSION: 'CHECK_USER_SESSION',
	SIGN_OUT_START: 'SIGN_OUT_START',
	SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
	SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
	SIGN_UP_START: 'SIGN_UP_START',
	SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
	SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
	RESET_ERROR: 'RESET_ERROR'
};

export default UserActionTypes;
